wandb_version: 1

name:
  desc: null
  value: UFPNet-GoPro
model_type:
  desc: null
  value: ImageRestorationModel
scale:
  desc: null
  value: 1
num_gpu:
  desc: null
  value: 6
manual_seed:
  desc: null
  value: 10
datasets:
  desc: null
  value:
    train:
      name: GoPro
      type: PairedImageDataset
      dataroot_gt: /raid/joowan/GoPro/train/sharp
      dataroot_lq: /raid/joowan/GoPro/train/sharp
      filename_tmpl: '{}'
      io_backend:
        type: disk
      gt_size: 256
      use_flip: true
      use_rot: true
      use_shuffle: true
      num_worker_per_gpu: 8
      batch_size_per_gpu: 1
      dataset_enlarge_ratio: 1
      prefetch_mode: cuda
      pin_memory: true
      phase: train
      scale: 1
    val:
      name: GoPro
      type: PairedImageDataset
      dataroot_gt: /raid/joowan/GoPro/train/sharp
      dataroot_lq: /raid/joowan/GoPro/train/sharp
      io_backend:
        type: disk
      phase: val
      scale: 1
network_g:
  desc: null
  value:
    type: UFPNet_code_uncertainty_Local
    width: 64
    enc_blk_nums:
    - 1
    - 1
    - 1
    - 28
    middle_blk_num: 1
    dec_blk_nums:
    - 1
    - 1
    - 1
    - 1
path:
  desc: null
  value:
    pretrain_network_g: null
    strict_load_g: true
    resume_state: null
    root: /home/joowan/Downloads/UFPDeblur
    experiments_root: /home/joowan/Downloads/UFPDeblur/experiments/UFPNet-GoPro
    models: /home/joowan/Downloads/UFPDeblur/experiments/UFPNet-GoPro/models
    training_states: /home/joowan/Downloads/UFPDeblur/experiments/UFPNet-GoPro/training_states
    log: /home/joowan/Downloads/UFPDeblur/experiments/UFPNet-GoPro
    visualization: /home/joowan/Downloads/UFPDeblur/experiments/UFPNet-GoPro/visualization
train:
  desc: null
  value:
    optim_g:
      type: AdamW
      lr: 0.001
      weight_decay: 0.001
      betas:
      - 0.9
      - 0.9
    scheduler:
      type: TrueCosineAnnealingLR
      T_max: 400000
      eta_min: 1.0e-07
    total_iter: 400000
    warmup_iter: -1
    pixel_opt:
      type: PSNRLoss
      loss_weight: 1
      reduction: mean
    reblur_opt:
      type: L1Loss
      loss_weight: 0.01
      reduction: mean
val:
  desc: null
  value:
    val_freq: 20000.0
    save_img: false
    metrics:
      psnr:
        type: calculate_psnr
        crop_border: 0
        test_y_channel: false
      ssim:
        type: calculate_ssim
        crop_border: 0
        test_y_channel: false
logger:
  desc: null
  value:
    print_freq: 200
    save_checkpoint_freq: 5000.0
    use_tb_logger: true
    wandb:
      project: UFP_Deblur
      resume_id: aodwndhks
dist_params:
  desc: null
  value:
    backend: nccl
    port: 29500
is_train:
  desc: null
  value: true
dist:
  desc: null
  value: false
rank:
  desc: null
  value: 0
world_size:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699926312.315641
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 35
      4: 3.8.17
      5: 0.15.8
      8:
      - 5
