# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: NAFNetKAM-GoPro-width64_dist
model_type: ImageRestorationModel
scale: 1
num_gpu: 4
manual_seed: ~

datasets:
  train:
    name: gopro-train
    type: PairedImageKernelDataset
    dataroot_gt: /raid/joowan/GoPro/train/sharp
    dataroot_lq: /raid/joowan/GoPro/train/blur
    dataroot_kernel: /raid/joowan/GoPro/train/kernel

    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 10
    batch_size_per_gpu: 10
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

    random_crop: True
    random_flip: True

  # val:
  #   name: gopro-test
  #   type: PairedImageDataset
  #   dataroot_gt: ./datasets/GoPro/test/target.lmdb
  #   dataroot_lq: ./datasets/GoPro/test/input.lmdb
  #   io_backend:
  #     type: lmdb


network_g:
  # type: UFPNet_code_uncertainty_Local
  type: NAFNet_KAM_Local
  width: 64
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 600000
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean
    
  reblur_opt:
    type: L1Loss
    loss_weight: 0.01
    reduction: mean

# validation settings
# val:
#   val_freq: ~
#   save_img: false


#   metrics:
#     psnr: # metric name, can be arbitrary
#       type: calculate_psnr
#       crop_border: 0
#       test_y_channel: false
#     ssim:
#       type: calculate_ssim
#       crop_border: 0
#       test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 30000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500